import { GenderEnum, authState } from ".";

export const initialState: authState = {
  token: "",
  deviceToken: "",
  netWorkState: false,
  trackingStatus: false,
  locationStatus: false,
  trackerInitlized: false,
  user: {
    fullName: "",
    driverName: "",
    profilepic: "",
    email: "",
    about: "",
    link: "",
    likes: 0,
    followers: 0,
    post: 0,
  },
  isLogin: false,
  signUpForm: {
    name: { value: "", errro: "" },
    phone: { value: "", errro: "" },
    email: { value: "", errro: "" },
    device_tocken: { value: "", errro: "" },
    profile_pic: { value: "", errro: "" },
  },
  loading: false,
  loginFrom: {
    mobileNumber: "",
    isMobileNumberValid: false,
    mobileVerify: false,
    countryCode: "",
    password: "",
  },
  userNotificion: [],
  OTPForm: {
    otp: 0,
  },
  hash: "",
  updatePassword: {
    confirmPassword: "",
    password: "",
  },
  childForm: {
    name: "",
    weekOfGestation: "",
    gender: GenderEnum.FEMALE,
    dob: "",
    profilePic: "",
    _id: "",
  },
  childList: [],
  profileForm: {
    email: "",
    name: "",
    dob: "",
    country: "",
    _id: "",
    gender: GenderEnum.FEMALE,
    relation: "",
    mobileNumber: "",
    otp: "",
    profilePic: "",
    isMobileNumberValid: false,
    mobileVerify: false,
    countryCode: "91",
    mobileNumberCheck: "",
    childAdded: false,
    emailVerified: false,
    profileCompleted: false,
  },
  profileList: [],
  loader: false,
  ParentForm: {
    email: "",
    name: "",
    dob: "",
    country: "",
    _id: "",
    gender: GenderEnum.FEMALE,
    relation: "",
    mobileNumber: "",
    otp: "",
    profilePic: "",
    isMobileNumberValid: false,
    mobileVerify: false,
    countryCode: "",
    mobileNumberCheck: "",
    childAdded: false,
    emailVerified: false,
    profileCompleted: false,
  },
  ParentList: [],
  googleLoginForm: { email: "", googleId: "", mobileNumber: "", name: "" },
  forgotPasswordEmail: {
    email: "", code: "", hash: "",
    mobileNumber: "",
    isMobileNumberValid: false,
    password: "",
    mobileVerify: false,
    countryCode: ""
  },
  googleLogin: { googleHash: "" }, googleLoading: false,
  plan: {},
  tutorial: ""
};
