export const SCREENS = {
  SIGNUP: "signup",
  PHONENUMBER: "phonenumber",
  CAR_DETAIL: "signup_car",
  CREATE_FAMILY: "create_family",
  EDIT_FAMILY: "Edit_family",
  ROOT: "root",
  DOC_REQUIRED: "doc_required",
  DOC_UPLOAD: "doc_upload",
  LOGIN: "login",
  OTP: "otp",
  PASSWORD: "password",
  PHYSICAL: "Physical",
  CREATE_PARENT: "create_parent",
  CREATE_CHILD: "create_child",
  FAMILY: "family",
  ADD_CHILD: "Add_Child",
  DEVELOPMENT_OF_SENSES: "DevelopmentOFSenses",
  EDIT_CHILD: "Edit_Child",
  KIDS: "Kids",
  HOME: "Home",
  MAIN: "Main",
  MILESTONE: "Milestone",
  PROGRESS: "Progress",
  MEALS: "Meals",
  COMMUNITY: "Community",
  SEARCH: "Search",
  SUPPORT_SCREEN: "support_screen",
  PAYMENT: "payment",
  PAYMENT_ADD: "payment_add",
  MENU: "menu",
  BOOKINGS: "bookings",
  SETTINGS: "settings",
  SEARCH_LOCATION: "search_location",
  SPLASH: "splash",
  CREATE_POST: "Create_Post",
  VERIFIED_OTP: "Verified_Otp",
  ONBOARD: "ONBOARD",
  TOYS: "Toys",
  ANALYTICS: "Analytics",
  PHOTO_VERIFY: "PhotoVerification",
  UNDER_VERIFY: "underVerification",
  BLOG_SCREEN: "Blogs",
  BLOG_DETAIL_SCREEN: "BlogsDetails",
  COMMUNITY_POST_SCREEN: "CommunityPost",
  COMMUNITY_POST_CREATE: "CommunityPostCreate",
  MEAL_LIST: "MealPlanner",
  COMMUNITY_POST_COMMENTS: "CommunityPostComment",
  COMMUNITY_POST_DETAILS: "CommunityPostDetails",
  ACITIVITY_DETAILS: "ActitityDetails",
  MEAL_DETAILS: "MealDetail",
  FILTER: "Filter",
  BMI_CALCULATE: "BmiCalculate",
  SLEEP: "Sleep",
  PLAN: "Plan",
  GROWTH: "Growth",
  FEEDING: "Feeding",
  BOTTELFEEDING: "BottelFeeding",
  ACTIVITYINMONTH: "ActivitiesInMonth",
  GROWTHANALYTICS: "GrowthAnalytics",
  COMPARISONOFMILESTONE: "ComparisonOfMilestone",
  SLEEPGRAPH: "SleepGraph",
  FEEDINGCHART: "FeedingcHART",
  CHAT : "Chat",
  VACCINATION: "Vaccination",
  TOY_FILTER :"ToyFilter",
  CONFIRM_VACCINATION: "ConfirmVaccination",
  NOTIFICATIONS: "Notifications",
  LANGUAGE:"Language",
 ASSESSMENT: "Assessment",
 FUNFOOD : "FunFoods",
 MEAL_FUN_FOOD_DETAILS: "MealsFunFoodDetail",
 UPDATE_PASSWORD:"UpdatePassword",
 FORGOT_PASSWORD:"Forgot Password",
 GOOGLE_PHONE_NUMBER:"GooglePhoneNumber",
 FORGOT_PASSWORD_CODE:"ForgotPasswordCode",
 MY_PROFILE:"MyProfile",
 FAQ:"faq",
 PROFILE_MENU:"MyProfileMenu",
 ALL_ACTIVITY:"AllActivity",
 ALL_MATERIAL:"AllMaterial",
 ALL_MEAL:"AllMeal",
 RATINGS:"Ratings",
 CATEGORY:"Category",
 TRACKING:"Tracking",
 TOYDETAIL :"ToyDetail",
 TRANSACTION :"Transaction",
 SUCCESS_SCREEN :"SuccessScreen",
 TUTORIAL: "Tutorial",
};

export const Constant = {
  USER_TOKEN: "user_token",
};
