import { BlogBookmarkEnum, BlogState } from ".";

export const initialState: BlogState = {
  blogs: [],
  favPosts: [],
  trendinggPosts: [],
  postCreated: false,
  postCommnets: [],
  filterCatgory: "",
  currentPage: 1,
  searchText: "",
  type: 1,
  bookmark: BlogBookmarkEnum.NO,
  category: "",
  meta: { limit: 10, page: 1, total: 0, totalPages: 0 },
  blogsDetails: {
    id: "",
    categoryid: "",
    category: "",
    title: "",
    description: "",
    age: 0,
    image: "",
    bookmark: BlogBookmarkEnum.NO,
    credits: 0,
    createdAt: "",
    userid: "",
    userName: "",
    profilepic: "",
    arabicShortDescription: "",
    arabicTitle: "",
    categoryId: "",
    englishShortDescription: "",
    englishTitle: "",
    hindiShortDescription: "",
    hindiTitle: "",
    _id: "",
    maxAge: 0,
    minAge: 0,
    arabicDescription: "",
    englishDescription: "",
    hindiDescription: "",
    isActive: 1,
    categoryArabicTitle: "",
    categoryEnglishTitle: "",
    categoryHindiTitle: "",
    type: 0,
    updatedAt: "",
    totalLikes: 0,
    like: 0,
  },
  categoryList: [],
  loading: true,
  moreLoading: false,
  randomData: []
};
