import { BlogBookmarkEnum, HomeActivityState } from '.';

export const initialState: HomeActivityState = {
  list: [],
  pageNo: 0,
  pageSize: 0,
  postCreated: false,
  filterCatgory: '',
  searchText: '',
  type: 1,
  bookmark: BlogBookmarkEnum.NO,
  category: "",
  details: {
    _id: "",
    englishTitle: "",
    hindiTitle: "",
    arabicTitle: "",
    image: "",
    englishPurpose: "",
    hindiPurpose: "",
    arabicPurpose: "",
    categoryId: "",
    milestoneId: "",
    englishVideo: "",
    hindiVideo: "",
    arabicVideo: "",
    englishDescription: "",
    hindiDescription: "",
    arabicDescription: "",
    englishMaterialList: [],
    hindiMaterialList: "",
    arabicMaterialList: "",
    visibleAge: 0,
    minAge: 0,
    maxAge: 0,
    isCompleted: false
  },
  categoryList: [],
  loading: true,
  toyList: [],
  MealList: [],
  date: new Date(),
  ActivityList: [],
  questionList: [],
  doCompleteQuestionList: [],
  MaterialDate: new Date(),
  ActivityDate: new Date()
};
