import { BookmarkEnum, ToyCurrencyEnum, ToysState } from ".";

export const initialState: ToysState = {
  Toys: [],
  pageNo: 0,
  pageSize: 10,
  totalRow: 0,
  searchText: "",
  filterCatgory: "",
  type: 0,
  bookmark: BookmarkEnum.NO,
  loading: true,
  category: "",
  ToyCategory: [],
  selectToyCategory: [],
  currentPage: 1,
  moreLoading: false,
  meta: {
    total: 0,
    page: 1,
    limit: 0,
    totalPages: 0,
  },

  search: "",
  randomData: [
    { id: "", item: [] },
    { id: "1", item: [] },
  ],
  toyDetails: {
    id: "",
    toysCategoryEnglishTitle: "",
    categoryEnglishTitle: "",
    categoryHindiTitle: "",
    categoryArabicTitle: "",
    shortEnglishDescription: "",
    shortHindiDescription: "",
    shortArabicDescription: "",
    minAge: "",
    maxAge: "",
    trending: undefined,
    toysCategory: "",
    arabicDescription: "",
    bookmark: BookmarkEnum.NO,
    categoryId: "",
    createdAt: "",
    currency: ToyCurrencyEnum.INR,
    englishDescription: "",
    hindiDescription: "",
    image: "",
    maxPrice: 0,
    minPrice: 0,
    productLink: "",
    updatedAt: "",
    _id: "",
    englishTitle: "",
    hindiTitle: "",
    arabicTitle: "",
  },
  ageFilter: {
    minAge: 0,
    maxAge: 0,
    isApplied: false,
    id: "",
  },
};
